mod conversions;
mod javascriptfile;
mod macros;
mod pyclass;
mod pydecl;
mod pyenums;
mod pyexpr;
mod pyfunction;
mod pyident;
mod pyjsx;
mod pylit;
mod pymodule;
mod pypat;
mod pyprop;
mod pyspan;
mod pystmts;
mod pytypeinfo;

use pyo3::prelude::*;
use pyo3::types::PyModule;

#[pymodule]
fn pyswc(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<javascriptfile::JavaScriptFile>()?;

    // pyspan.rs
    m.add_class::<pyspan::PySpan>()?;
    // pyenums.rs
    m.add_class::<pyenums::PyUnaryOp>()?;
    m.add_class::<pyenums::PyAssignOp>()?;
    m.add_class::<pyenums::PyUpdateOp>()?;
    m.add_class::<pyenums::PyBinaryOp>()?;
    m.add_class::<pyenums::PyTsKeywordTypeKind>()?;
    m.add_class::<pyenums::PyTruePlusMinus>()?;
    m.add_class::<pyenums::PyTsTypeOperatorOp>()?;
    m.add_class::<pyenums::PyAccessibility>()?;
    m.add_class::<pyenums::PyMethodKind>()?;
    m.add_class::<pyenums::PyVarDeclKind>()?;
    m.add_class::<pyenums::PyImportPhase>()?;
    m.add_class::<pyenums::PyMetaPropKind>()?;
    // pyident.rs
    m.add_class::<pyident::PyBindingIdent>()?;
    m.add_class::<pyident::PyIdent>()?;
    m.add_class::<pyident::PyIdentName>()?;
    m.add_class::<pyident::PyPrivateName>()?;
    // pylit.rs
    m.add_class::<pylit::PyLit>()?;
    // pyfunction.rs
    m.add_class::<pyfunction::PyCallee>()?;
    m.add_class::<pyfunction::PyDecorator>()?;
    m.add_class::<pyfunction::PyFunction>()?;
    m.add_class::<pyfunction::PyFunctionBody>()?;
    m.add_class::<pyfunction::PyParam>()?;
    m.add_class::<pyfunction::PyTsThisParam>()?;
    // pypat.rs
    m.add_class::<pypat::PyArrayPat>()?;
    m.add_class::<pypat::PyAssignPat>()?;
    m.add_class::<pypat::PyAssignPatProp>()?;
    m.add_class::<pypat::PyBindingIdentPat>()?;
    m.add_class::<pypat::PyExprPat>()?;
    m.add_class::<pypat::PyInvalidPat>()?;
    m.add_class::<pypat::PyKeyValuePatProp>()?;
    m.add_class::<pypat::PyObjectPat>()?;
    m.add_class::<pypat::PyObjectPatProp>()?;
    m.add_class::<pypat::PyObjectPatRestProp>()?;
    m.add_class::<pypat::PyPat>()?;
    m.add_class::<pypat::PyRestPat>()?;
    // pyprop.rs
    m.add_class::<pyprop::PyAssignProp>()?;
    m.add_class::<pyprop::PyBigIntPropName>()?;
    m.add_class::<pyprop::PyComputedPropName>()?;
    m.add_class::<pyprop::PyExprOrSpread>()?;
    m.add_class::<pyprop::PyGetterProp>()?;
    m.add_class::<pyprop::PyIdentPropName>()?;
    m.add_class::<pyprop::PyKeyValueProp>()?;
    m.add_class::<pyprop::PyMemberProp>()?;
    m.add_class::<pyprop::PyMethodProp>()?;
    m.add_class::<pyprop::PyNumPropName>()?;
    m.add_class::<pyprop::PyProp>()?;
    m.add_class::<pyprop::PyPropName>()?;
    m.add_class::<pyprop::PyPropOrSpread>()?;
    m.add_class::<pyprop::PyPropOrSpreadProp>()?;
    m.add_class::<pyprop::PySetterProp>()?;
    m.add_class::<pyprop::PyShorthandProp>()?;
    m.add_class::<pyprop::PySpreadElement>()?;
    m.add_class::<pyprop::PyStrPropName>()?;
    m.add_class::<pyprop::PySuperProp>()?;
    // pyexpr.rs
    m.add_class::<pyexpr::PyArrayLitExpr>()?;
    m.add_class::<pyexpr::PyArrowExpr>()?;
    m.add_class::<pyexpr::PyArrowFunctionBody>()?;
    m.add_class::<pyexpr::PyAssignExpr>()?;
    m.add_class::<pyexpr::PyAssignTarget>()?;
    m.add_class::<pyexpr::PyAssignTargetPat>()?;
    m.add_class::<pyexpr::PyAssignTargetSimple>()?;
    m.add_class::<pyexpr::PyAwaitExpr>()?;
    m.add_class::<pyexpr::PyBinExpr>()?;
    m.add_class::<pyexpr::PyCallExpr>()?;
    m.add_class::<pyexpr::PyClassExpr>()?;
    m.add_class::<pyexpr::PyCondExpr>()?;
    m.add_class::<pyexpr::PyExpr>()?;
    m.add_class::<pyexpr::PyFnExpr>()?;
    m.add_class::<pyexpr::PyIdentExpr>()?;
    m.add_class::<pyexpr::PyInvalidExpr>()?;
    m.add_class::<pyexpr::PyLitExpr>()?;
    m.add_class::<pyexpr::PyMemberExpr>()?;
    m.add_class::<pyexpr::PyMetaPropExpr>()?;
    m.add_class::<pyexpr::PyNewExpr>()?;
    m.add_class::<pyexpr::PyObjectLit>()?;
    m.add_class::<pyexpr::PyOptCall>()?;
    m.add_class::<pyexpr::PyOptChainBase>()?;
    m.add_class::<pyexpr::PyOptChainBaseMember>()?;
    m.add_class::<pyexpr::PyOptChainExpr>()?;
    m.add_class::<pyexpr::PyParenExpr>()?;
    m.add_class::<pyexpr::PyPrivateNameExpr>()?;
    m.add_class::<pyexpr::PySeqExpr>()?;
    m.add_class::<pyexpr::PySimpleAssignTarget>()?;
    m.add_class::<pyexpr::PySimpleAssignTargetIdent>()?;
    m.add_class::<pyexpr::PySimpleAssignTargetInvalid>()?;
    m.add_class::<pyexpr::PySuper>()?;
    m.add_class::<pyexpr::PySuperPropExpr>()?;
    m.add_class::<pyexpr::PyTaggedTpl>()?;
    m.add_class::<pyexpr::PyThisExpr>()?;
    m.add_class::<pyexpr::PyTpl>()?;
    m.add_class::<pyexpr::PyTsAsExpr>()?;
    m.add_class::<pyexpr::PyTsConstAssertion>()?;
    m.add_class::<pyexpr::PyTsInstantiation>()?;
    m.add_class::<pyexpr::PyTsNonNullExpr>()?;
    m.add_class::<pyexpr::PyTsSatisfiesExpr>()?;
    m.add_class::<pyexpr::PyTsTypeAssertion>()?;
    m.add_class::<pyexpr::PyUnaryExpr>()?;
    m.add_class::<pyexpr::PyUpdateExpr>()?;
    m.add_class::<pyexpr::PyYieldExpr>()?;
    // pystmts.rs
    m.add_class::<pystmts::PyBlockStmt>()?;
    m.add_class::<pystmts::PyBreakStmt>()?;
    m.add_class::<pystmts::PyCatchClause>()?;
    m.add_class::<pystmts::PyContinueStmt>()?;
    m.add_class::<pystmts::PyDebuggerStmt>()?;
    m.add_class::<pystmts::PyDeclStmt>()?;
    m.add_class::<pystmts::PyDoWhileStmt>()?;
    m.add_class::<pystmts::PyEmptyStmt>()?;
    m.add_class::<pystmts::PyExprStmt>()?;
    m.add_class::<pystmts::PyForHead>()?;
    m.add_class::<pystmts::PyForInStmt>()?;
    m.add_class::<pystmts::PyForOfStmt>()?;
    m.add_class::<pystmts::PyForStmt>()?;
    m.add_class::<pystmts::PyIfStmt>()?;
    m.add_class::<pystmts::PyLabeledStmt>()?;
    m.add_class::<pystmts::PyReturnStmt>()?;
    m.add_class::<pystmts::PyStmt>()?;
    m.add_class::<pystmts::PySwitchCase>()?;
    m.add_class::<pystmts::PySwitchStmt>()?;
    m.add_class::<pystmts::PyThrowStmt>()?;
    m.add_class::<pystmts::PyTryStmt>()?;
    m.add_class::<pystmts::PyVarDeclOrExpr>()?;
    m.add_class::<pystmts::PyWhileStmt>()?;
    m.add_class::<pystmts::PyWithStmt>()?;
    // pytypeinfo.rs
    m.add_class::<pytypeinfo::PyTplElement>()?;
    m.add_class::<pytypeinfo::PyTsArrayType>()?;
    m.add_class::<pytypeinfo::PyTsCallSignatureDecl>()?;
    m.add_class::<pytypeinfo::PyTsConditionalType>()?;
    m.add_class::<pytypeinfo::PyTsConstructorType>()?;
    m.add_class::<pytypeinfo::PyTsConstructSignatureDecl>()?;
    m.add_class::<pytypeinfo::PyTsEntityName>()?;
    m.add_class::<pytypeinfo::PyTsExprWithTypeArgs>()?;
    m.add_class::<pytypeinfo::PyTsFnType>()?;
    m.add_class::<pytypeinfo::PyTsGetterSignature>()?;
    m.add_class::<pytypeinfo::PyTsImportCallOptions>()?;
    m.add_class::<pytypeinfo::PyTsImportType>()?;
    m.add_class::<pytypeinfo::PyTsIndexedAccessType>()?;
    m.add_class::<pytypeinfo::PyTsIndexSignature>()?;
    m.add_class::<pytypeinfo::PyTsInferType>()?;
    m.add_class::<pytypeinfo::PyTsIntersectionType>()?;
    m.add_class::<pytypeinfo::PyTsKeywordType>()?;
    m.add_class::<pytypeinfo::PyTsLit>()?;
    m.add_class::<pytypeinfo::PyTsLitBigInt>()?;
    m.add_class::<pytypeinfo::PyTsLitBool>()?;
    m.add_class::<pytypeinfo::PyTsLitNumber>()?;
    m.add_class::<pytypeinfo::PyTsLitStr>()?;
    m.add_class::<pytypeinfo::PyTsLitTpl>()?;
    m.add_class::<pytypeinfo::PyTsLitType>()?;
    m.add_class::<pytypeinfo::PyTsMappedType>()?;
    m.add_class::<pytypeinfo::PyTsMethodSignature>()?;
    m.add_class::<pytypeinfo::PyTsOptionalType>()?;
    m.add_class::<pytypeinfo::PyTsParenthesizedType>()?;
    m.add_class::<pytypeinfo::PyTsPropertySignature>()?;
    m.add_class::<pytypeinfo::PyTsQualifiedName>()?;
    m.add_class::<pytypeinfo::PyTsRestType>()?;
    m.add_class::<pytypeinfo::PyTsSetterSignature>()?;
    m.add_class::<pytypeinfo::PyTsThisType>()?;
    m.add_class::<pytypeinfo::PyTsThisTypeOrIdent>()?;
    m.add_class::<pytypeinfo::PyTsThisTypeOrIdentIdent>()?;
    m.add_class::<pytypeinfo::PyTsThisTypeOrIdentThis>()?;
    m.add_class::<pytypeinfo::PyTsTupleElement>()?;
    m.add_class::<pytypeinfo::PyTsTupleType>()?;
    m.add_class::<pytypeinfo::PyTsType>()?;
    m.add_class::<pytypeinfo::PyTsTypeAnn>()?;
    m.add_class::<pytypeinfo::PyTsTypeElement>()?;
    m.add_class::<pytypeinfo::PyTsTypeLit>()?;
    m.add_class::<pytypeinfo::PyTsTypeOperator>()?;
    m.add_class::<pytypeinfo::PyTsTypeParam>()?;
    m.add_class::<pytypeinfo::PyTsTypeParamDecl>()?;
    m.add_class::<pytypeinfo::PyTsTypeParamInstantiation>()?;
    m.add_class::<pytypeinfo::PyTsTypePredicate>()?;
    m.add_class::<pytypeinfo::PyTsTypeQuery>()?;
    m.add_class::<pytypeinfo::PyTsTypeQueryExpr>()?;
    m.add_class::<pytypeinfo::PyTsTypeQueryExprEntityName>()?;
    m.add_class::<pytypeinfo::PyTsTypeQueryExprImport>()?;
    m.add_class::<pytypeinfo::PyTsTypeRef>()?;
    m.add_class::<pytypeinfo::PyTsUnionType>()?;
    // pyclass.rs
    m.add_class::<pyclass::PyAutoAccessor>()?;
    m.add_class::<pyclass::PyClass>()?;
    m.add_class::<pyclass::PyClassEmptyMember>()?;
    m.add_class::<pyclass::PyClassIndexSignature>()?;
    m.add_class::<pyclass::PyClassMember>()?;
    m.add_class::<pyclass::PyClassMethod>()?;
    m.add_class::<pyclass::PyClassProp>()?;
    m.add_class::<pyclass::PyConstructor>()?;
    m.add_class::<pyclass::PyKey>()?;
    m.add_class::<pyclass::PyParamOrTsParamProp>()?;
    m.add_class::<pyclass::PyParamOrTsParamPropParam>()?;
    m.add_class::<pyclass::PyParamOrTsParamPropTsParamProp>()?;
    m.add_class::<pyclass::PyPrivateMethod>()?;
    m.add_class::<pyclass::PyPrivateProp>()?;
    m.add_class::<pyclass::PyStaticBlock>()?;
    // pydecl.rs
    m.add_class::<pydecl::PyClassDecl>()?;
    m.add_class::<pydecl::PyDecl>()?;
    m.add_class::<pydecl::PyFnDecl>()?;
    m.add_class::<pydecl::PyTsEnumDecl>()?;
    m.add_class::<pydecl::PyTsEnumMember>()?;
    m.add_class::<pydecl::PyTsInterfaceBody>()?;
    m.add_class::<pydecl::PyTsInterfaceDecl>()?;
    m.add_class::<pydecl::PyTsModuleBlock>()?;
    m.add_class::<pydecl::PyTsModuleDecl>()?;
    m.add_class::<pydecl::PyTsModuleName>()?;
    m.add_class::<pydecl::PyTsNamespaceBody>()?;
    m.add_class::<pydecl::PyTsNamespaceDecl>()?;
    m.add_class::<pydecl::PyTsTypeAliasDecl>()?;
    m.add_class::<pydecl::PyUsingDecl>()?;
    m.add_class::<pydecl::PyVarDecl>()?;
    m.add_class::<pydecl::PyVarDeclarator>()?;
    // pymodule.rs
    m.add_class::<pymodule::PyDefaultDecl>()?;
    m.add_class::<pymodule::PyDefaultDeclClass>()?;
    m.add_class::<pymodule::PyDefaultDeclFn>()?;
    m.add_class::<pymodule::PyDefaultDeclTsInterface>()?;
    m.add_class::<pymodule::PyExportAll>()?;
    m.add_class::<pymodule::PyExportDecl>()?;
    m.add_class::<pymodule::PyExportDefaultDecl>()?;
    m.add_class::<pymodule::PyExportDefaultExpr>()?;
    m.add_class::<pymodule::PyExportDefaultSpecifier>()?;
    m.add_class::<pymodule::PyExportNamedSpecifier>()?;
    m.add_class::<pymodule::PyExportNamespaceSpecifier>()?;
    m.add_class::<pymodule::PyExportSpecifier>()?;
    m.add_class::<pymodule::PyImportDecl>()?;
    m.add_class::<pymodule::PyImportDefaultSpecifier>()?;
    m.add_class::<pymodule::PyImportNamedSpecifier>()?;
    m.add_class::<pymodule::PyImportSpecifier>()?;
    m.add_class::<pymodule::PyImportStarAsSpecifier>()?;
    m.add_class::<pymodule::PyModuleDecl>()?;
    m.add_class::<pymodule::PyModuleExportName>()?;
    m.add_class::<pymodule::PyModuleItem>()?;
    m.add_class::<pymodule::PyModuleItemDecl>()?;
    m.add_class::<pymodule::PyModuleItemStmt>()?;
    m.add_class::<pymodule::PyNamedExport>()?;
    m.add_class::<pymodule::PySourceModule>()?;
    m.add_class::<pymodule::PyTsExportAssignment>()?;
    m.add_class::<pymodule::PyTsExternalModuleRef>()?;
    m.add_class::<pymodule::PyTsImportEqualsDecl>()?;
    m.add_class::<pymodule::PyTsModuleRef>()?;
    m.add_class::<pymodule::PyTsNamespaceExportDecl>()?;
    // pyjsx.rs
    m.add_class::<pyjsx::PyJSXAttr>()?;
    m.add_class::<pyjsx::PyJSXAttrName>()?;
    m.add_class::<pyjsx::PyJSXAttrOrSpread>()?;
    m.add_class::<pyjsx::PyJSXAttrOrSpreadAttr>()?;
    m.add_class::<pyjsx::PyJSXAttrOrSpreadSpread>()?;
    m.add_class::<pyjsx::PyJSXAttrValue>()?;
    m.add_class::<pyjsx::PyJSXAttrValueElement>()?;
    m.add_class::<pyjsx::PyJSXAttrValueExprContainer>()?;
    m.add_class::<pyjsx::PyJSXAttrValueFragment>()?;
    m.add_class::<pyjsx::PyJSXAttrValueStr>()?;
    m.add_class::<pyjsx::PyJSXClosingElement>()?;
    m.add_class::<pyjsx::PyJSXClosingFragment>()?;
    m.add_class::<pyjsx::PyJSXElement>()?;
    m.add_class::<pyjsx::PyJSXElementChild>()?;
    m.add_class::<pyjsx::PyJSXElementChildElement>()?;
    m.add_class::<pyjsx::PyJSXElementChildExprContainer>()?;
    m.add_class::<pyjsx::PyJSXElementChildFragment>()?;
    m.add_class::<pyjsx::PyJSXElementChildSpreadChild>()?;
    m.add_class::<pyjsx::PyJSXElementChildText>()?;
    m.add_class::<pyjsx::PyJSXElementName>()?;
    m.add_class::<pyjsx::PyJSXEmptyExpr>()?;
    m.add_class::<pyjsx::PyJSXExpr>()?;
    m.add_class::<pyjsx::PyJSXExprContainer>()?;
    m.add_class::<pyjsx::PyJSXFragment>()?;
    m.add_class::<pyjsx::PyJSXMemberExpr>()?;
    m.add_class::<pyjsx::PyJSXMemberExprData>()?;
    m.add_class::<pyjsx::PyJSXNamespacedName>()?;
    m.add_class::<pyjsx::PyJSXNamespacedNameData>()?;
    m.add_class::<pyjsx::PyJSXObject>()?;
    m.add_class::<pyjsx::PyJSXOpeningElement>()?;
    m.add_class::<pyjsx::PyJSXOpeningFragment>()?;
    m.add_class::<pyjsx::PyJSXSpreadChild>()?;

    Ok(())
}
